### ISSUE TITLE
This Demo app(Live-shop) is not worked! Please, help asap!

### ISSUE THREAD

**Issue by tasoolove37** [AgoraIO/Live-Shop-Use-Case#6]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int io.agora.rtc.RtcEngine.setChannelProfile(int)' on a null object reference
        at io.agora.liveshop.rtc.RtcEngineManager.init(RtcEngineManager.java:52)
        at io.agora.liveshop.activities.LiveRoomActivity.onAllPermissionsGranted(LiveRoomActivity.java:326)
        at io.agora.liveshop.activities.BaseActivity$1.onPermissionAlreadyGranted(BaseActivity.java:28)
        at io.agora.liveshop.utils.PermissionUtil.checkPermissionsIfNeeded(PermissionUtil.java:37)
        at io.agora.liveshop.activities.BaseActivity.onCreate(BaseActivity.java:24)
        at io.agora.liveshop.activities.LiveRoomActivity.onCreate(LiveRoomActivity.java:217)

**Comment by plutoless** [comment]
looks like your engine is a null pointer. could you pls help trace the code to see why?

**Comment by tasoolove37** [comment]
Thanks!

But now i have many other bug in my app.
Please, help me asap!!!

------------------------------------------------
import com.bs.tasooapp.rtc.RtcEngineManager;
import com.bs.tasooapp.utils.PermissionUtil;

D:\Android_project\tasoo_app\app\src\main\java\com\bs\tasooapp\BaseActivity.java:11: error: package com.bs.tasooapp.rtc does not exist
import com.bs.tasooapp.rtc.RtcEngineManager;

------------------------------------------------------------
import com.bs.tasooapp.data.Product; <-- Bug(data)
-------------------------------------------------------------
